@startuml
scale 1500 width
[*] --> CLI

state CLI {
  [*] --> Idle
  Idle --> CollectdGenericJmx : Pass input to perform configuration transfiguration
}

state CollectdGenericJmx {
    [*] --> GenericJmxCompleteChainedTransfiguration

    state GenericJmxCompleteChainedTransfiguration {
        [*] --> SpliByApplicationTransfiguration
        SpliByApplicationTransfiguration -> GenericJmxApplicationChainedTransfiguration : foreach application

        state GenericJmxApplicationChainedTransfiguration {
            [*] ---> PrepareAppConfTransfiguration
            PrepareAppConfTransfiguration -> ConfReaderToContextTransfiguration
            ConfReaderToContextTransfiguration -> GenericJmxAttributeChainedTransfiguration : '1. mbean'
            ConfReaderToContextTransfiguration -> GenericJmxAttributeChainedTransfiguration : '2. connection'

            state GenericJmxAttributeChainedTransfiguration {
                [*] ---> GenericJmxGenerateTemplateNameWithPyST
                GenericJmxGenerateTemplateNameWithPyST -> GenericJmxInputToStubWithJinja2
                GenericJmxInputToStubWithJinja2 -> GenericJmxStubToOutputViaJinja2
            }

            GenericJmxAttributeChainedTransfiguration ---> GenericJmxApplicationChainedTransfiguration
        }

        GenericJmxApplicationChainedTransfiguration -> SpliByApplicationTransfiguration
        SpliByApplicationTransfiguration -> GenericJmxConsolidateToFinalOutput
    }

    GenericJmxCompleteChainedTransfiguration --> CollectdGenericJmx
}

CollectdGenericJmx --> [*] : Success
@enduml